<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\GirderSchedule.Domain\GirderSchedule.Domain.csproj" />
        <ProjectReference Include="..\ScheduleTools.Excel\ScheduleTools.Excel.csproj" />
    </ItemGroup>

</Project>
