//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GirderSchedule.App.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GirderSchedule.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   선택한 층과 하위 부재가 모두 삭제됩니다.
        ///삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_DeleteSelectedFloorWithMembersConfirm {
            get {
                return ResourceManager.GetString("Content_DeleteSelectedFloorWithMembersConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 부재를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_DeleteSelectedMemberConfirm {
            get {
                return ResourceManager.GetString("Content_DeleteSelectedMemberConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DXF 템플릿 파일을 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_DxfTemplateFileNotFound {
            get {
                return ResourceManager.GetString("Content_DxfTemplateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보내기가 완료되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_ExportCompleted {
            get {
                return ResourceManager.GetString("Content_ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 여는 중 오류가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_FileOpenFailedWithError {
            get {
                return ResourceManager.GetString("Content_FileOpenFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일을 저장할 수 없습니다.
        ///저장하려는 파일이 다른 프로그램에서 열려 있을 수 있습니다.
        ///파일을 닫은 뒤 다시 저장해 주세요.
        ///
        ///파일 경로 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_FileSaveFailedFileOpened {
            get {
                return ResourceManager.GetString("Content_FileSaveFailedFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일을 저장할 권한이 없습니다.
        ///쓰기 권한이 있는 폴더인지 확인하거나 다른 위치에 저장해 주세요.
        ///
        ///파일 경로 : {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_FileSaveFailedNoPermission {
            get {
                return ResourceManager.GetString("Content_FileSaveFailedNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 저장 중 오류가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_FileSaveFailedWithError {
            get {
                return ResourceManager.GetString("Content_FileSaveFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   층 이름을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_InputFloorName {
            get {
                return ResourceManager.GetString("Content_InputFloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 이름을 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_InputProjectName {
            get {
                return ResourceManager.GetString("Content_InputProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보낼 부재가 선택되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_NoExportTargetSelected {
            get {
                return ResourceManager.GetString("Content_NoExportTargetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은 이름의 프로젝트 파일이 이미 있습니다.
        ///덮어쓰시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_ProjectAlreadyExistsOverwrite {
            get {
                return ResourceManager.GetString("Content_ProjectAlreadyExistsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 파일이 아직 저장되지 않았습니다.
        ///내보내기 전에 프로젝트를 먼저 저장해야 합니다.
        ///프로젝트를 저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_ProjectSaveRequiredBeforeExportConfirm {
            get {
                return ResourceManager.GetString("Content_ProjectSaveRequiredBeforeExportConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 파일이 존재하지 않습니다.
        ///최근 목록에서 제거했습니다.
        ///
        ///{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_RecentProjectFileMissing {
            get {
                return ResourceManager.GetString("Content_RecentProjectFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 위치를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_SelectProjectFolder {
            get {
                return ResourceManager.GetString("Content_SelectProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작할 프로젝트를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_SelectProjectOpen {
            get {
                return ResourceManager.GetString("Content_SelectProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가로 개수는 1 이상으로 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_TotalColumnCountMustBeAtLeastOne {
            get {
                return ResourceManager.GetString("Content_TotalColumnCountMustBeAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장하지 않은 변경 내용이 있습니다.
        ///저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Content_UnsavedChangesSaveConfirm {
            get {
                return ResourceManager.GetString("Content_UnsavedChangesSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트를 저장할 폴더를 선택하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Description_SelectProjectSaveFolder {
            get {
                return ResourceManager.GetString("Description_SelectProjectSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   층 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteFloor {
            get {
                return ResourceManager.GetString("Title_DeleteFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   부재 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_DeleteMember {
            get {
                return ResourceManager.GetString("Title_DeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보내기 완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ExportCompleted {
            get {
                return ResourceManager.GetString("Title_ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보내기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ExportFailed {
            get {
                return ResourceManager.GetString("Title_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_FileNotFound {
            get {
                return ResourceManager.GetString("Title_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   층 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_FloorSetting {
            get {
                return ResourceManager.GetString("Title_FloorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_Help {
            get {
                return ResourceManager.GetString("Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 프로젝트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_NewProject {
            get {
                return ResourceManager.GetString("Title_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_OpenProject {
            get {
                return ResourceManager.GetString("Title_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 열기 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_OpenProjectFailed {
            get {
                return ResourceManager.GetString("Title_OpenProjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ProjectSave {
            get {
                return ResourceManager.GetString("Title_ProjectSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 저장 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ProjectSaveFailed {
            get {
                return ResourceManager.GetString("Title_ProjectSaveFailed", resourceCulture);
            }
        }
    }
}
