<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
	  <Folder Include="MVVM\" />
	  <Folder Include="Behaviors\" />
	  <Folder Include="Dialogs\" />
	  <Folder Include="Themes\" />
	  <Folder Include="Utilities\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ScheduleTools.Core\ScheduleTools.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Home\Views\ProjectCreateWindow.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="Settings\Views\AppSettingWindow.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>
</Project>
