<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GirderSchedule.Dxf</RootNamespace>
    <AssemblyName>GirderSchedule.Dxf</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="netDxf" Version="2023.11.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GirderSchedule.Domain\GirderSchedule.Domain.csproj" />
  </ItemGroup>

</Project>