<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>GirderSchedule.App</RootNamespace>
		<AssemblyName>GirderSchedule.App</AssemblyName>
		<ApplicationIcon>Resources\ganadi_icon_multi.ico</ApplicationIcon>

		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Resources\**" />
		<EmbeddedResource Remove="Resources\**" />
		<Compile Remove="Resource\**" />
		<EmbeddedResource Remove="Resource\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\GirderTemplate.bak" />
	  <None Remove="Resources\GirderTemplate.dwg" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GirderSchedule.Domain\GirderSchedule.Domain.csproj" />
		<ProjectReference Include="..\GirderSchedule.Dxf\GirderSchedule.Dxf.csproj" />
		<ProjectReference Include="..\GirderSchedule.Excel\GirderSchedule.Excel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Resources\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\GirderTemplate.dxf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>


	<ItemGroup>
		<None Update="Resource\GriderScheduleTemplate.dxf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
